services:
    PoP\UserRolesAccessControl\TypeResolverDecorators\:
        resource: '../src/TypeResolverDecorators/*'
        public: true

    PoP\UserRolesAccessControl\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true
